version: '3'

services:
  nodemongo:
    build: ./
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database
    restart: always
  
  database: 
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always
