version: '2'

services:
  nodemongo:
    build: ./
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  
  database: 
    image: mongo
    volumes:
      - ./data/db:/data/db